### ISSUE TITLE
Job Board HQM Quest idea

### ISSUE THREAD

**Issue by teagan75** [GreatOrator/TolkienCraftII-Map#5]
1. Create a quest that once they come through the portal to middle earth it completes the location quest. Can even do this for the Overworld fetch quests for each town.
2. Title them Job Board: Overworld and Job Board: Middle Earth
   Overworld would simply be connected to the existing quests in the book, and pretty much unlock everything, based on completion (i.e. killed the mobs, killed the troll, etc). Middle Earth can be linked to the locations and as players complete those new jobs become available
3. Quest opens up that suggests the player make their way to wherever to see the "news" board for middle earth. Maybe, (possibly using a carriage and driver as tp NPC) teleport player to the "job board"  or town crier in that town, etc.
4. Hide and show dialogs based on the main quest line or location reached. Talk to crier or interact someway to the board, he/she/it tells you the NPC to talk to in the location to finish quest. An item or location could trigger another job in a new location.

**Comment by GreatOrator** [comment]
I will start testing things out for this in the next day or so and see what we can come up with.

My thoughts are to reconfigure the existing "journal" section and then create the two new ones mentioned.  The journal was supposed to just track quests completed for the player (which is why the items are required) but we can use these points in the journal to unlock the job board idea

would make it so adding new NPC's would not be necessary but would still help to direct players to new sections/quest beyond the main quest line

**Comment by GreatOrator** [comment]
wow, I was so busy I totally forgot about this...will try to remember tonight (since this has to be tested on my local copy)

**Comment by GreatOrator** [comment]
Done!  Will be a part of the next update :)
